### ISSUE TITLE
why use pointer manipulation instead of get_unchecked()?

### ISSUE THREAD

**Issue by trinity-1686a** [ktkaufman03/static-slicing#2]
Hi,
while reading your [blog post](https://ktkaufman03.github.io/blog/2023/04/20/rust-compile-time-checks/) about this crate, I wondered why you choose pointer manipulation over `get_unchecked()`
```rust
unsafe { &*(self.as_ptr().add(INDEX) as *const T) }
// vs
unsafe { self.get_unchecked(I) }
```
And I have the same question for subslicing (though it's partially answered by the blog post already)
> It looks weird. If I know something can’t fail, why am I “trying” to do it?

```rust
unsafe { &*(self.as_ptr().add(START) as *const [T; LENGTH])}
vs
unsafe { self.get_unchecked(START..START+LENGTH)}.try_into().unwrap()
```
I've checked, and both time they seems to generate the same machine code.

Anyway, nice trick! I'm not sure if I'll end up using it anywhere, but I will sure keep it in mind!

**Comment by ktkaufman03** [comment]
Good question. The pointer manipulation is simply what I came up with first, so I kept it around. In my local repository, I've already changed it to `get_unchecked`, and that change will be released at some point.
